package: emailobfuscator
version: '2.0.0'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/emailobfuscator

page:
    title: 'translate:title'
    perm: emailobfuscator[]
    pjax: true
    icon: rex-icon fa-lock
    subpages:
        config: { title: 'translate:config', perm: emailobfuscator[config] }